# Generated by Django 3.1.1 on 2020-09-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestresponse',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='responses', verbose_name='Иллюстрация отзыва'),
        ),
    ]
